// <auto-generated />
using System;
using ApiServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321145219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiServer.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BuiltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BuiltById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FortressId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("BuiltById");

                    b.HasIndex("FortressId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ApiServer.Models.BuildingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ProductionRate")
                        .HasColumnType("real");

                    b.Property<int>("UnlockTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameWorldId");

                    b.ToTable("BuildingTypes");
                });

            modelBuilder.Entity("ApiServer.Models.Fortress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaptureThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("DifficultyTier")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFinalObjective")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameWorldId");

                    b.HasIndex("ParentId");

                    b.ToTable("Fortresses");
                });

            modelBuilder.Entity("ApiServer.Models.GameWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameWorlds");
                });

            modelBuilder.Entity("ApiServer.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OAuthId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OAuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OAuthProvider", "OAuthId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ApiServer.Models.PlayerContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BuildingTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameWorldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetFortressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("GameWorldId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TargetFortressId");

                    b.ToTable("PlayerContributions");
                });

            modelBuilder.Entity("ApiServer.Models.Building", b =>
                {
                    b.HasOne("ApiServer.Models.BuildingType", "BuildingType")
                        .WithMany("Buildings")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.Player", "BuiltBy")
                        .WithMany()
                        .HasForeignKey("BuiltById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.Fortress", "Fortress")
                        .WithMany()
                        .HasForeignKey("FortressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("BuiltBy");

                    b.Navigation("Fortress");
                });

            modelBuilder.Entity("ApiServer.Models.BuildingType", b =>
                {
                    b.HasOne("ApiServer.Models.GameWorld", "GameWorld")
                        .WithMany("BuildingTypes")
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameWorld");
                });

            modelBuilder.Entity("ApiServer.Models.Fortress", b =>
                {
                    b.HasOne("ApiServer.Models.GameWorld", "GameWorld")
                        .WithMany("Fortresses")
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.Fortress", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GameWorld");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ApiServer.Models.PlayerContribution", b =>
                {
                    b.HasOne("ApiServer.Models.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.GameWorld", "GameWorld")
                        .WithMany()
                        .HasForeignKey("GameWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.Fortress", "TargetFortress")
                        .WithMany()
                        .HasForeignKey("TargetFortressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("GameWorld");

                    b.Navigation("Player");

                    b.Navigation("TargetFortress");
                });

            modelBuilder.Entity("ApiServer.Models.BuildingType", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("ApiServer.Models.Fortress", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ApiServer.Models.GameWorld", b =>
                {
                    b.Navigation("BuildingTypes");

                    b.Navigation("Fortresses");
                });
#pragma warning restore 612, 618
        }
    }
}
